# Generated by Django 5.1.4 on 2025-09-22 06:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_productreview_dislikes_productreview_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
